apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "wikijs.fullname" . }}
  name: {{ template "wikijs.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wikijs.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "wikijs.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ template "wikijs.fullname" . }}
        envFrom:
          - secretRef:
              name: {{ template "wikijs.fullname" . }}
        volumeMounts:
        - mountPath: /wiki/config.yml
          subPath: config.yml
          name: config-volume
          readOnly: true
      volumes:
      - configMap:
          name: {{ template "wikijs.fullname" . }}
        name: config-volume