apiVersion: v1
kind: Service
metadata:
  name: {{ template "wikijs.fullname" . }}
  labels:
    app: {{ template "wikijs.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ template "wikijs.fullname" . }}
  type: ClusterIP
