apiVersion: v1
data:
  DB_HOST: {{ template "postgres.fullname" . }}
  DB_PORT: {{ .Values.dbConfig.port | quote | b64enc }}
  DB_TYPE: {{ .Values.dbConfig.type | b64enc }}
  DB_NAME: {{ .Values.dbConfig.name | b64enc }}
  DB_USER: {{ .Values.dbConfig.user | b64enc }}
  DB_PASS: {{ .Values.dbConfig.pass | b64enc }}
kind: Secret
metadata:
  name: {{ template "wikijs.fullname" . }} 
